#!/usr/bin/env node
/**
 * shared-memory bridge — 命令行桥接，供 agent 通过 exec 调用
 * 
 * 用法:
 *   node bridge.js write '{"content":"...", "source":"openclaw"}'
 *   node bridge.js search '{"query":"ROS", "limit":5}'
 *   node bridge.js query '{"type":"core", "depth":"deep", "limit":10}'
 *   node bridge.js anchors
 *   node bridge.js summary
 *   node bridge.js get <id>
 *   node bridge.js delete <id>
 *   node bridge.js archive <anchorId>
 *   node bridge.js unarchive <anchorId>
 *   node bridge.js auto-archive
 */

const { writeMemory } = require('./lib/memory.js');
const { getMemory, queryMemories, search, searchDeep, listAnchors, searchAnchors, listSummary, getAnchor } = require('./lib/search.js');
const { deleteMemory, batchDelete, expireShallow, listRecycle, restoreFromRecycle } = require('./lib/delete.js');
const { archiveAnchor, unarchiveAnchor, searchArchive, listArchive, archiveStats, autoArchive } = require('./lib/archive.js');

const cmd = process.argv[2];
const arg = process.argv[3];

function out(obj) {
  console.log(JSON.stringify(obj, null, 2));
}

async function main() {
  try {
    switch (cmd) {
      case 'write': {
        const input = JSON.parse(arg);
        // 默认写 shallow，除非用户显式指定 opts.shallow=false
        if (!input.options) input.options = {};
        if (!input.options.forceDepth && input.opts?.shallow !== false) {
          input.options.forceDepth = 'shallow';
        }
        // 冲突检测：检查是否有相似锚点
        const existingAnchors = listAnchors();
        const content20 = (input.content || '').slice(0, 20);
        const similarAnchors = existingAnchors.filter(a => 
          a.summary && a.summary.includes(content20.slice(0, 10))
        );
        
        const result = writeMemory(input);
        
        if (similarAnchors.length > 0) {
          result.conflict = {
            detected: true,
            similar_anchors: similarAnchors.map(a => ({
              anchor_id: a.anchor_id,
              summary: a.summary,
              type: a.type
            })),
            instruction: '⚠️ 发现可能冲突的锚点，请向老公汇报，由他决断'
          };
        }
        
        out(result);
        break;
      }
      
      case 'search': {
        const { query, limit = 5 } = JSON.parse(arg);
        out(search(query, { limit }));
        break;
      }
      
      case 'search-deep': {
        const { query, limit = 5, minScore = 0.1, excludeAutoGenerated } = JSON.parse(arg);
        out(searchDeep(query, { limit, minScore, excludeAutoGenerated }));
        break;
      }
      
      case 'query': {
        const opts = JSON.parse(arg);
        out(queryMemories(opts));
        break;
      }
      
      case 'anchors': {
        out(listAnchors());
        break;
      }
      
      case 'anchor': {
        out(getAnchor(arg));
        break;
      }
      
      case 'summary': {
        const opts = arg ? JSON.parse(arg) : { limit: 20 };
        out(listSummary(opts));
        break;
      }
      
      case 'get': {
        out(getMemory(arg));
        break;
      }
      
      case 'delete': {
        out(deleteMemory(arg));
        break;
      }
      
      case 'batch-delete': {
        out(batchDelete(JSON.parse(arg)));
        break;
      }
      
      case 'expire': {
        out(expireShallow());
        break;
      }
      
      case 'recycle': {
        out(listRecycle());
        break;
      }
      
      case 'restore': {
        out(restoreFromRecycle(arg));
        break;
      }
      
      case 'archive': {
        out(archiveAnchor(arg));
        break;
      }
      
      case 'unarchive': {
        out(unarchiveAnchor(arg));
        break;
      }
      
      case 'auto-archive': {
        out(autoArchive());
        break;
      }
      
      case 'archive-list': {
        out(listArchive());
        break;
      }
      
      case 'archive-stats': {
        out(archiveStats());
        break;
      }
      
      case 'archive-search': {
        const { query } = JSON.parse(arg);
        out(searchArchive(query));
        break;
      }
      
      default:
        out({ error: '未知命令: ' + cmd, usage: 'write|search|query|anchors|summary|get|delete|archive|unarchive|...' });
    }
  } catch (e) {
    out({ error: e.message, stack: e.stack });
    process.exit(1);
  }
}

main();
