/**
 * 记忆系统 — 检索模块
 *
 * 提供浅度记忆和深度记忆的检索功能。
 * 浅度：时间范围 + 关键词精确匹配
 * 深度：语义相似度检索（初期 TF-IDF 兜底，后期可升级 embedding）
 */

const { getDb } = require('./db');
const nodejieba = require('nodejieba');

// ============================================================
// 自定义词典 — 技术术语确保正确分词
// ============================================================
const CUSTOM_WORDS = [
  "底核型", "浅度记忆", "深度记忆", "共享记忆", "用户画像",
  "记忆系统", "工作模式", "智能体", "多智能体", "语义搜索",
  "锚点机制", "提取精华", "向量搜索", "混合搜索",
  "STM32", "F407", "ROS2", "HAL", "FTS5",
  "OpenClaw", "Hermes", "DeepSeek", "Bridge",
  "nodejieba", "TF-IDF", "BM25", "RRF", "HNSW",
  "I2C", "PWM", "GPIO", "SPI", "UART", "ADC", "DMA", "CAN",
];
for (const w of CUSTOM_WORDS) {
  nodejieba.insertWord(w);
}

// ============================================================
// 一、单条读取
// ============================================================

/**
 * 按 ID 获取单条记忆
 * @param {string} id
 * @returns {object|null} 记忆记录或 null
 */
function getMemory(id) {
  const db = getDb();
  const row = db.prepare('SELECT * FROM memories WHERE id = ?').get(id);
  if (!row) return null;
  return parseRow(row);
}

/**
 * 获取当前所有未过期的记忆（快速总览）
 * @param {object} [opts] - { depth, type, limit }
 */
function getAllMemories(opts = {}) {
  const db = getDb();
  const { depth, type, limit = 50 } = opts;
  const conditions = [];
  const params = [];

  // 默认只查未过期的记录
  conditions.push(`(expire_at IS NULL OR expire_at > datetime('now'))`);

  if (depth) {
    conditions.push('depth = ?');
    params.push(depth);
  }
  if (type) {
    conditions.push('type = ?');
    params.push(type);
  }

  const sql = `SELECT * FROM memories WHERE ${conditions.join(' AND ')} ORDER BY timestamp DESC LIMIT ?`;
  params.push(limit);

  const rows = db.prepare(sql).all(...params);
  return rows.map(parseRow);
}

// ============================================================
// 二、条件检索（浅度检索通道）
// ============================================================

/**
 * 条件检索记忆
 *
 * @param {object} filters
 * @param {string}  [filters.type]       - 'core' | 'emotion'
 * @param {string}  [filters.depth]      - 'shallow' | 'deep' | 'archived'
 * @param {string}  [filters.keyword]    - 关键词模糊匹配（搜索 keywords JSON 字段）
 * @param {string}  [filters.source]     - 'openclaw' | 'hermes' | 'manual'
 * @param {string}  [filters.timeFrom]   - ISO8601 起始时间
 * @param {string}  [filters.timeTo]     - ISO8601 截止时间
 * @param {number}  [filters.limit=50]   - 返回条数
 * @param {number}  [filters.offset=0]   - 偏移量（分页）
 * @param {boolean} [filters.includeExpired=false] - 是否包含过期记录
 * @param {string}  [filters.searchText] - 搜索摘要/详情文本（LIKE 模糊匹配）
 * @param {boolean} [filters.excludeAutoGenerated=false] - 是否排除自动生成的对话摘要
 * @returns {object[]}
 */
function queryMemories(filters = {}) {
  // 后过滤：排除自动生成的对话摘要
  const _noAuto = filters.excludeAutoGenerated;
  const db = getDb();
  const conditions = [];
  const params = [];

  // 类型
  if (filters.type) {
    conditions.push('type = ?');
    params.push(filters.type);
  }

  // 深度
  if (filters.depth) {
    conditions.push('depth = ?');
    params.push(filters.depth);
  }

  // 来源
  if (filters.source) {
    conditions.push('source = ?');
    params.push(filters.source);
  }

  // 关键词（JSON 字符串 + 摘要 + 详情中模糊匹配）
  if (filters.keyword) {
    conditions.push("(keywords LIKE ? OR summary LIKE ? OR detail LIKE ?)");
    params.push(`%${filters.keyword}%`, `%${filters.keyword}%`, `%${filters.keyword}%`);
  }

  // 时间范围
  if (filters.timeFrom) {
    conditions.push('timestamp >= ?');
    params.push(filters.timeFrom);
  }
  if (filters.timeTo) {
    conditions.push('timestamp <= ?');
    params.push(filters.timeTo);
  }

  // 过期过滤
  if (!filters.includeExpired) {
    conditions.push(`(expire_at IS NULL OR expire_at > datetime('now'))`);
  }

  // 文本搜索（摘要 + 详情）
  if (filters.searchText) {
    conditions.push('(summary LIKE ? OR detail LIKE ?)');
    params.push(`%${filters.searchText}%`, `%${filters.searchText}%`);
  }

  const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
  const sql = `${whereClause} ORDER BY timestamp DESC LIMIT ? OFFSET ?`;

  const limit = filters.limit || 50;
  const offset = filters.offset || 0;
  params.push(limit, offset);

  let rows = db.prepare(`SELECT * FROM memories ${sql}`).all(...params);
  rows = rows.map(parseRow);

  // 后过滤：排除自动生成的对话摘要
  if (_noAuto) {
    rows = rows.filter(r => {
      const s = (r.summary || '').slice(0, 100);
      // autoSummary() 生成的摘要格式：'💡 对话摘要...' 或 '💗 对话摘要...'
      return !s.includes('对话摘要');
    });
  }

  return rows;
}

/**
 * 快速搜索入口：自动判断走浅度还是深度通道
 *
 * @param {string} query - 搜索词
 * @param {object} [options]
 * @param {boolean} [options.excludeAutoGenerated=false] - 是否排除自动生成的对话摘要
 * @returns {object[]}
 */
function search(query, options = {}) {
  if (!query || !query.trim()) return [];

  // 短查询、含精确关键词 → 走浅度通道（关键词 + 文本 LIKE）
  const isExact = query.length < 10 && !/[？。，、；：！…—]/.test(query);

  if (options.depth === 'shallow' || (isExact && !options.depth)) {
    let results = queryMemories({
      searchText: query,
      keyword: query,
      ...options,
    });
    // 浅搜也加上评分，方便排序和展示
    const queryTerms = tokenize(query);
    if (queryTerms.length > 0) {
      results = results.map(r => {
        const full = `${r.summary || ''} ${r.detail || ''}`;
        const docTerms = tokenize(full);
        return { ...r, score: cosineSimilarity(queryTerms, docTerms) };
      });
      results.sort((a, b) => b.score - a.score);
    }
    // 浅搜没结果时自动降级到深搜通道（jieba分词匹配，不要求连续）
    if (results.length === 0 && queryTerms.length > 0) {
      return searchDeep(query, options);
    }
    return results;
  }

  // 长查询 / 明确要求深度 → 走深度语义通道（初期用 TF-IDF 兜底）
  if (options.depth === 'deep' || (!isExact && !options.depth)) {
    return searchDeep(query, options);
  }

  return queryMemories({ searchText: query, ...options });
}

// ============================================================
// 三、深度检索（初期 TF-IDF 兜底）
// ============================================================

/**
 * 深度语义检索（TF-IDF 余弦相似度）
 *
 * 当前实现：基于关键词 + 文本重叠的简单评分
 * 升级路径：后期用 embedding 模型替换
 *
 * @param {string} query - 查询文本
 * @param {object} [options] - { limit, type, excludeAutoGenerated }
 * @returns {object[]} 按相似度降序
 */
function searchDeep(query, options = {}) {
  const _noAuto = options.excludeAutoGenerated;
  const db = getDb();
  const { limit = 10, type } = options;

  // 获取候选记录
  const conditions = ["depth IN ('deep', 'archived')"];
  const params = [];

  if (type) {
    conditions.push('type = ?');
    params.push(type);
  }

  const rows = db.prepare(`
    SELECT * FROM memories
    WHERE ${conditions.join(' AND ')}
    ORDER BY timestamp DESC
  `).all(...params);

  // 对每条记录计算与 query 的相似度
  const queryStr = typeof query === 'object' ? (query.keyword || '') : String(query || '');
  const queryTerms = queryStr ? tokenize(queryStr) : [];
  const scored = rows.map(row => {
    const full = `${row.summary} ${row.detail} ${row.keywords}`;
    const docTerms = tokenize(full);
    const score = cosineSimilarity(queryTerms, docTerms);
    return { ...parseRow(row), score };
  });

  // 按分数降序
  scored.sort((a, b) => b.score - a.score);

  let result = scored.slice(0, limit);

  // 后过滤：排除自动生成的对话摘要
  if (_noAuto) {
    result = result.filter(r => {
      const s = (r.summary || '').slice(0, 100);
      return !s.includes('对话摘要');
    });
  }

  return result;
}

// ============================================================
// 四、锚点检索
// ============================================================

/**
 * 获取锚点及其关联的所有记忆
 * @param {string} anchorId
 * @returns {object|null} { anchor, memories: [] }
 */
function getAnchor(anchorId) {
  const db = getDb();

  const anchor = db.prepare('SELECT * FROM anchors WHERE anchor_id = ?').get(anchorId);
  if (!anchor) return null;

  const memories = db.prepare(`
    SELECT m.* FROM memories m
    JOIN anchor_refs r ON m.id = r.memory_id
    WHERE r.anchor_id = ?
    ORDER BY m.timestamp DESC
  `).all(anchorId);

  return {
    anchor,
    memories: memories.map(parseRow),
  };
}

/**
 * 获取锚点关联的记忆（仅列表）
 * @param {string} anchorId
 * @returns {object[]}
 */
function getAnchorMemories(anchorId) {
  const db = getDb();
  const rows = db.prepare(`
    SELECT m.* FROM memories m
    JOIN anchor_refs r ON m.id = r.memory_id
    WHERE r.anchor_id = ?
    ORDER BY m.timestamp DESC
  `).all(anchorId);
  return rows.map(parseRow);
}

/**
 * 列出所有锚点
 * @param {object} [opts] - { type, limit }
 * @returns {object[]}
 */
function listAnchors(opts = {}) {
  const db = getDb();
  const conditions = [];
  const params = [];

  if (opts.type) {
    conditions.push('type = ?');
    params.push(opts.type);
  }

  const whereClause = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
  const limit = opts.limit || 50;

  const rows = db.prepare(`
    SELECT a.*, COUNT(r.memory_id) as ref_count
    FROM anchors a
    LEFT JOIN anchor_refs r ON a.anchor_id = r.anchor_id
    ${whereClause}
    GROUP BY a.anchor_id
    ORDER BY a.updated_at DESC
    LIMIT ?
  `).all(...params, limit);

  return rows;
}

/**
 * 搜索锚点（基于摘要 + 关键词模糊匹配）
 * @param {string} query
 * @param {object} [opts]
 * @returns {object[]}
 */
function searchAnchors(query, opts = {}) {
  const db = getDb();
  const conditions = ['(summary LIKE ? OR keywords LIKE ?)'];
  const params = [`%${query}%`, `%${query}%`];

  if (opts.type) {
    conditions.push('type = ?');
    params.push(opts.type);
  }

  const limit = opts.limit || 20;
  const rows = db.prepare(`
    SELECT a.*, COUNT(r.memory_id) as ref_count
    FROM anchors a
    LEFT JOIN anchor_refs r ON a.anchor_id = r.anchor_id
    WHERE ${conditions.join(' AND ')}
    GROUP BY a.anchor_id
    ORDER BY a.updated_at DESC
    LIMIT ?
  `).all(...params, limit);

  return rows;
}

// ============================================================
// 五、摘要列表（快速概览）
// ============================================================

/**
 * 获取记忆摘要列表（只返回 summary + 关键字段，轻量级）
 * @param {object} [opts] - { type, depth, limit }
 * @returns {object[]}
 */
function listSummary(opts = {}) {
  const db = getDb();
  const conditions = ["(expire_at IS NULL OR expire_at > datetime('now'))"];
  const params = [];

  if (opts.type) { conditions.push('type = ?'); params.push(opts.type); }
  if (opts.depth) { conditions.push('depth = ?'); params.push(opts.depth); }

  const limit = opts.limit || 30;
  const rows = db.prepare(`
    SELECT id, type, depth, timestamp, summary, keywords, anchor_id
    FROM memories
    WHERE ${conditions.join(' AND ')}
    ORDER BY timestamp DESC
    LIMIT ?
  `).all(...params, limit);

  return rows;
}

// ============================================================
// 六、内部工具
// ============================================================

/**
 * 解析行数据：将 keywords 从 JSON 字符串解析为数组
 */
function parseRow(row) {
  if (!row) return null;
  try {
    row.keywords = JSON.parse(row.keywords || '[]');
  } catch {
    row.keywords = [];
  }
  return row;
}

/**
 * 中文分词（基于 nodejieba）
 * 提取有实际意义的中文词 + 英文单词
 */
const STOP_WORDS = new Set([
  "我", "你", "他", "她", "它", "我们", "你们", "他们", "她们", "它们",
  "的", "了", "是", "在", "有", "和", "就", "不", "也", "都", "这", "那",
  "吗", "啊", "呢", "吧", "呀", "哦", "嗯", "哈", "嘿", "哎", "喂",
  "一个", "这个", "那个", "什么", "怎么", "为什么", "因为", "所以",
  "但是", "然后", "而且", "或者", "如果", "虽然", "可以", "没有",
  "不是", "还是", "就是", "只是", "但是", "还是", "觉得", "知道",
  "说", "看", "想", "到", "了", "过", "着", "让", "把", "被", "从",
  "又", "再", "还", "已经", "可能", "应该", "要", "会", "能",
  "跟", "对", "给", "为", "向", "以", "与", "及", "等", "或", "并",
  "上", "下", "中", "前", "后", "里", "外", "多", "少", "很", "太",
  "非常", "比较", "最", "更", "越", "稍", "略", "将", "可",
  "其", "之", "所", "被", "把", "让", "使", "令",
  "的", "地", "得", "着", "过", "了", "呢",
  "去", "来", "做", "搞", "弄", "打",
]);

function tokenize(text) {
  if (!text) return [];
  const terms = [];

  // jieba 中文分词
  const words = nodejieba.cut(text);
  for (const w of words) {
    const trimmed = w.trim();
    // 过滤：停用词、单字（除英文外）、纯标点
    if (!trimmed || trimmed.length < 1) continue;
    if (/^[\u4e00-\u9fff]+$/.test(trimmed)) {
      // 中文词：去掉停用词和单字
      if (trimmed.length >= 2 && !STOP_WORDS.has(trimmed)) {
        terms.push(trimmed);
      }
    } else if (/^[a-zA-Z0-9]+$/.test(trimmed)) {
      // 英文/数字：只保留长度 >= 2 的（跳过单字母、单数字）
      if (trimmed.length >= 2) {
        terms.push(trimmed.toLowerCase());
      }
    }
    // 其他（混合、符号）→ 忽略
  }

  // 额外提取英文单词（处理 jieba 可能漏切的英文连词）
  const engWords = text.toLowerCase().match(/[a-zA-Z][a-zA-Z0-9_-]*/g) || [];
  for (const w of engWords) {
    if (w.length >= 2 && !terms.includes(w)) {
      terms.push(w);
    }
  }

  return terms;
}

/**
 * 计算两个词袋的余弦相似度
 */
function cosineSimilarity(termsA, termsB) {
  if (termsA.length === 0 || termsB.length === 0) return 0;

  // 构建词频向量
  const freqA = {};
  const freqB = {};
  const allTerms = new Set();

  for (const t of termsA) { freqA[t] = (freqA[t] || 0) + 1; allTerms.add(t); }
  for (const t of termsB) { freqB[t] = (freqB[t] || 0) + 1; allTerms.add(t); }

  let dotProduct = 0;
  let magA = 0;
  let magB = 0;

  for (const term of allTerms) {
    const a = freqA[term] || 0;
    const b = freqB[term] || 0;
    dotProduct += a * b;
    magA += a * a;
    magB += b * b;
  }

  if (magA === 0 || magB === 0) return 0;
  return dotProduct / (Math.sqrt(magA) * Math.sqrt(magB));
}

// ============================================================
// 七、导出
// ============================================================

module.exports = {
  getMemory,
  getAllMemories,
  queryMemories,
  search,
  searchDeep,
  getAnchor,
  getAnchorMemories,
  listAnchors,
  searchAnchors,
  listSummary,
  // 工具方法也导出，方便测试/调试
  tokenize,
  cosineSimilarity,
};
